version: "3.7"
services:
  mealie:
    container_name: mealie
    image: hkotel/mealie:v0.5.6
    restart: unless-stopped
    ports:
      - ${APP_PORT}:80
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    networks:
      - tipi_main_network
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.mealie.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.mealie.entrypoints: websecure
      traefik.http.routers.mealie.service: mealie
      traefik.http.routers.mealie.tls.certresolver: myresolver
      traefik.http.services.mealie.loadbalancer.server.port: 80