version: "3.7"
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:0.10.7
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/config:/app/data/configs
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${APP_PORT}:7575
    networks:
      - tipi_main_network
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.homarr.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.homarr.entrypoints: websecure
      traefik.http.routers.homarr.service: homarr
      traefik.http.routers.homarr.tls.certresolver: myresolver
      traefik.http.services.homarr.loadbalancer.server.port: 7575
